'use client';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  paragraphId: string;
  generatedBy: string;
  visible: boolean;
  onAccept: (id: string) => void;
  onReject: (id: string) => void;
}

export default function GhostOverlay({ paragraphId, generatedBy, visible, onAccept, onReject }: Props) {
  return (
    <AnimatePresence>
      {visible && (
        <motion.div
          className="flex items-center gap-2 py-1.5"
          initial={{ opacity: 0, y: -4 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -4 }}
          transition={{ duration: 0.18 }}
        >
          <button
            onClick={() => onAccept(paragraphId)}
            className="px-2.5 py-1 rounded font-mono text-[9.5px] border bg-green-50 border-green-200 text-green-800 hover:bg-green-700 hover:text-white hover:border-green-700 transition-all"
          >
            ✓ Accept Draft
          </button>
          <button
            onClick={() => onReject(paragraphId)}
            className="px-2.5 py-1 rounded font-mono text-[9.5px] border bg-red-50 border-red-200 text-red-800 hover:bg-red-700 hover:text-white hover:border-red-700 transition-all"
          >
            ✕ Discard
          </button>
          <span className="font-mono text-[9px] text-[var(--text-3)]">
            Generated by {generatedBy}
          </span>
          <span className="font-mono text-[9px] text-[var(--text-3)] ml-auto">
            ⌘↵ Accept · ⌘⌫ Discard
          </span>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
